version: '3'
services:
  app: 
    image: hatsapol/app:1.0.0
    container_name: my-app
    ports: 
      - ${APP_PORTS}
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
    networks:
      - menter
  db:
    image: postgres:latest
    container_name: my-db
    ports: 
      - ${DB_PORTS}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - menter
networks:
  menter: